### ISSUE TITLE
 Accessibility issues with CheckboxGroup 

### ISSUE THREAD

**Issue by rupeshpadhye** [tenon-io/tenon-ui#25]
Can Checkbox group  traversed with arrow keys currently tab button takes to next

**Comment by AlmeroSteyn** [comment]
@rupeshpadhye Thank you for taking an interest and logging this.

We find it to be standard browser behaviour that `TAB` moves focus to the next checkbox while `SHIFT+TAB` moves focus to the previous checkbox. `Spacebar` is then used to select / deselect the checkbox, while `Enter` will submit the form as this is standard browser behaviour for any form that contains a `button of type="submit"`.

Using arrow keys is a pattern for a group of **radio buttons** instead.

If we override the arrow keys to set focus on checkboxes we will hijack browser scroll behaviour and this will cause confusion for some users as this is not expected behaviour according to the specification.

In effect a group of checkboxes are simply unique checkbox controls grouped together under one heading using a fieldset. Their function should remain unchanged.

For each checkbox the [APG for checkboxes](https://www.w3.org/TR/wai-aria-practices-1.1/#checkbox) applies.

In the light of this I am closing this issue.
